### ISSUE TITLE
Problem when using in next.js

### ISSUE THREAD

**Issue by yuenengc** [elchininet/postcss-rtlcss#101] opened 2021-09-23 08:21 UTC
postcss.config.js like this
`module.exports = {
  plugins: ['postcss-rtlcss']
}`

and the packages version
` "postcss": "^8.1.1",
    "postcss-loader": "^4.0.3",
    "postcss-rtlcss": "3.0.0",`

it failed to compile as below:

`ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'config'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }

> Build error occurred`

How can I use postcss-rtlcss in nextjs project properly?

**Comment by elchininet** [comment] 2021-09-23 08:50
[Since version 3.0.0](https://github.com/elchininet/postcss-rtlcss/issues/53), `postcss-rtlcss` is compatible with NextJs. Looking at your error message it seems that the error is not related to the plugin itself. Are you using a custom Webpack config?. Could you create a minimum reproducible repo to check the issue live?

**Comment by elchininet** [comment] 2021-09-23 08:59
I pushed a minimum Nextjs project to [this repo](https://github.com/elchininet/nextjs-postcss-rtlcss-example). Please, could you try to reproduce your issue there?

**Comment by yuenengc** [comment] 2021-09-24 08:35
@elchininet Thanks for the quick response, the example you provided can build successfully. 
And I have removed my custom Webpack config(sorry for ignoring that) which cause the issue I mentioned above. 
But now I get a new issue using the same config as the example:
`TypeError: Invalid PostCSS Plugin found at: plugins[0](@postcss.config.js)
    at Array.forEach (<anonymous>)`
and I haven't found a way to repo it in the example yet, just FYI

**Comment by elchininet** [comment] 2021-09-24 08:53
Most probably what was wrong with your Wbpack config [was this](https://github.com/webpack-contrib/postcss-loader/issues/472).

I pushed a change to the repo [providing your same configuration](https://github.com/elchininet/nextjs-postcss-rtlcss-example/blob/master/postcss.config.js) and it also builds without any issue.

[Checking this issue](https://github.com/postcss/postcss/issues/1615) and [this another issue](https://github.com/tailwindlabs/tailwindcss/issues/2795) in the `postcss` repo, maybe it is caused by a wrong `postcss` or `postcss-loader` version installed, but it would be hard to assure it without debugging it properly. You can fork the repo, create a branch and submit your changes to reproduce the issue, then it should be easier to investigate.

**Comment by yuenengc** [comment] 2021-09-26 14:32
@elchininet Thanks a lot, I have checked the issue you metioned and it would cause by the different version of postcss. In my project it uses @zeit/next-css@1.0.1(deprecated) required postcss which version is below v8.

**Comment by elchininet** [comment] 2021-09-26 17:05
Hi @yuenengc,
`Next.js` already has CSS support, you don‘t need to use `@zeit/next-css` anymore. Try to remove this package and check if your project builds this time.
Let me know if you solve it to close the issue.
Regards

**Comment by elchininet** [comment] 2021-09-29 16:35
Hi @yuenengc,
Did you solve the issue?
Regards.

**Comment by elchininet** [comment] 2021-10-05 20:19
Hi @yuenengc, closing this issue.
If you face another issue, please, open a new one.
Regards.

**Closed by elchininet** 2021-10-05 20:19 UTC

**Comment by yuenengc** [comment] 2021-10-11 06:53
@elchininet Sorry for late reply, I took a long holiday. The issue may not cause by this plugin so I'm trying other way in the project. Thanks anyway！
