### ISSUE TITLE
Support to include some files or packages

### ISSUE THREAD

**Issue by Leruiz** [elchininet/postcss-rtlcss#68] opened 2021-03-31 09:25 UTC
We need to handle RTL for a part area. But now all css will be processed. Could `include` or. `exclude` option be supported?

**Comment by elchininet** [comment] 2021-03-31 13:18
Hi @Leruiz, could you share what tool/configuration are you using?

A small repo with an example of your configuration would be appreciated.

**Comment by elchininet** [comment] 2021-04-27 11:49
Hi @Leruiz, it seems that you already find a solution for your issue.
Closing this issue.

**Closed by elchininet** 2021-04-27 11:49 UTC
Labels: question, request

**Comment by Saeid-Za** [comment] 2021-05-02 10:01
Hello and thanks for the library ! 
I have the same request here. Here's the scenario:
While developing RTL web pages There are 3rd party libraries that only support LTR. using this library we could trasform these libraries to corresponding RTL versions.
but this transformation should only be applied to 3rd party libraries, not my CSS files.

So there should be an option to include / exclude files from applying these transformations.

**Comment by elchininet** [comment] 2021-05-02 10:22
Hi @Saeid-Za,

As I asked @Leruiz, could you share what tool/configuration are you using or a small repo with your configuration?

The reason for this is that this tool is just a `postcss` plugin. It is `postcss` which processes the files and applies to those files the plugins that you have chosen. Normally `postcss` is used through other tools (Webpack, Gulp, Grunt, etc) and these tools have configurations to decide how to process your files.

**Comment by Saeid-Za** [comment] 2021-05-02 10:48
@elchininet Thanks for responding.
I see, this is rather a postcss scoped request than a postcss plugin request.
I'm using webpack and `postcss-loader` for writing this include / exclude functionality.

```js
const postcssRTL = require('postcss-rtlcss')

const postCssOpts = { plugins: [] }
const customPlugin = ctx => {
  const plugins = []
  const isVendorCss = vendorCssPaths.every(item => ctx.source.input.file.indexOf(item) === -1)
  plugins.push(postcssRTL({source: isVendorCss ? 'ltr' : 'rtl'}))
  return plugins
}

postCssOpts.plugins.push(customPlugin)

rule.use('postcss-loader')
  .loader('postcss-loader')
  .options(postCssOpts)
```

**Comment by elchininet** [comment] 2021-05-02 10:57
@Saeid-Za exactly, from `postcss` the plugin receives a `root` object and its task is to modify it. But deciding which file to process falls in an upper level.

It seems then that this configuration that you are using doesn't work. Do you have a public repo with your project to check it out?

**Comment by Saeid-Za** [comment] 2021-05-02 11:08
i'm using [Quasar](https://github.com/quasarframework/quasar), and recently it has been updated to a new version.
in this update quasar switching from `postcss-rtl` to `postcss-rtlcss` as it's primary RTL transformer.
unfortunately this new version, has a bug in transformation compared to previous version.
  
the snippet I posted earlier, was from the newer version (with some changes), Here's the original [file](https://github.com/quasarframework/quasar/blob/dev/app/lib/webpack/inject.style-rules.js#L89) 
and here's the old working [file](https://github.com/quasarframework/quasar/blob/master/app/lib/webpack/inject.style-rules.js#L89). 

same principles were applied in both versions, if an specific condition was met, transformer would change it's assumption on direction on input CSS file.

**Comment by elchininet** [comment] 2021-05-02 11:15
I'll check Quasar and your snippets to see if I can reproduce the issue. But just to double check, do you want to exclude some files from being processed by `postcss-rtlcss` or do you want to process all the files and just changing the `source` attribute per file?

**Comment by Saeid-Za** [comment] 2021-05-02 11:18
Thanks ! I want to process all files and change `source` pre case.

**Comment by elchininet** [comment] 2021-05-02 11:50
I don't see any usage of `postcss-rtlcss` in Quasar, could you point me out to the specific commit?

And another question, how do you include the vendor CSS files? I can't find any reference to `vendorCssPaths` in the snippets that you shared.

**Comment by Saeid-Za** [comment] 2021-05-03 03:21
Hello !
I had changed the original file a bit to decrease the noise and irrelevant codes, that's why this is not a match to quasar's own file, and one of the links in the previous comment was pointing to a wrong file (i've updated it), sorry for confusion.
After several hours of doing some trial and error, i've found out that `postcss` APIs had been changed from the previous version that quasar was depending on.

postcss config that are loaded with `postcss-loader` can either be an[ object or a function](https://webpack.js.org/loaders/postcss-loader/), returning that object. one of the fields in the returned object is plugin. 
previously this plugin could be a function, returning the plugin data, that's how the old working syntax was doing fine. it seems this behavior was changed in latest version of postcss / postcss-loader ([Here](https://github.com/webpack-contrib/postcss-loader/issues/494) and [Here](https://github.com/webpack-contrib/postcss-loader/issues/495)).
The solution that I found out was to use the postcss config function to manipulate the returned config of plugin, somthing like this (in webpack,js):

```js
const postcssRTL = require('postcss-rtlcss')

module.exports = {
  module: {
    rules: [
      {
        test: /\.(css|sss)$/i,
        loader: "postcss-loader",
        options: {

          postcssOptions: (loaderContext) => {
            if (/\.sss$/.test(loaderContext.resourcePath)) {
              // assuming we have a list of 3rd party css libraries that we want to apply rtlcss on.
              const isVendorCss = vendorCssList.some(item => ctx.resourcePath.indexOf(item) === -1)
              return {
                plugins: [
                    postcssRTL({ source: isVendorCss ? 'ltr' : 'rtl' })
                ],
              };
            }
          },

        },
      },
    ],
  },
};

```

Thanks for helping me and again Thanks for this amazing library.

**Comment by elchininet** [comment] 2021-05-03 17:56
Oh, I'm glad that you solved it.
Another solution would be using [Rule.resourceQuery](https://webpack.js.org/configuration/module/#ruleresourcequery) to execute a specific set of rules in the files that you want, but I think that your solution is clearer.
