### ISSUE TITLE
Types don't work with allowJs: true and require()

### ISSUE THREAD

**Issue by catrope** [elchininet/postcss-rtlcss#128] opened 2022-03-25 22:20 UTC
If I enable `"allowJs": true` and `"checkJs": true` in my `tsconfig.json`, TypeScript will do type checking in JavaScript files like `postcss.confg.js`. However, postcss-rtlcss's type definitions break in this case:

```js
const postcssRtlcss = require( 'postcss-rtlcss' );
const autoprefixer = require( 'autoprefixer' );

module.exports = {
    plugins: [
        postcssRtlcss(),
        autoprefixer()
    ]
};
```

This results in the following TypeScript error:
```
postcss.config.js:12:3 - error TS2349: This expression is not callable.
  Type 'typeof import("/home/catrope/[...]/node_modules/postcss-rtlcss/index")' has no call signatures.

12   postcssRtlcss()
     ~~~~~~~~~~~~~
```

If I use `require( 'postcss-rtlcss').default`, then TypeScript is happy, but of course I get a runtime error because that property doesn't exist in reality.

For `autoprefixer` everything does work correctly. It looks like the critical difference is that postcss-rtlcss uses `export default blah;` but autoprefixer uses `export = blah;`.

**Comment by elchininet** [comment] 2022-03-26 01:25
Hi @catrope,
This is due to how the types are exported in the `d.ts` files at the moment. I‘m refactoring the package to provide a `commonjs` and a `esm` version of it. When this is ready, you will not have this issue anymore, for now you can juts ignore the line with `@ts-ignore`. I‘ll let you know when it is ready, I‘ll let this issue open.
Regards

**Comment by elchininet** [comment] 2022-03-26 01:57
@catrope, about this part:

>For `autoprefixer` everything does work correctly. It looks like the critical difference is that postcss-rtlcss uses `export default blah;` but autoprefixer uses `export = blah;`.

I think that you are looking at [the type definition file of autoprefixer](https://github.com/postcss/autoprefixer/blob/main/lib/autoprefixer.d.ts#L95) instead of [the real module](https://github.com/postcss/autoprefixer/blob/main/lib/autoprefixer.js#L57).

**Comment by elchininet** [comment] 2022-03-26 21:31
Hi @catrope,
I‘ve released a new version of the package. Now, two bundles are generated using `Rollup`, one for `esm` and one for `CommonJs`, the type definitions should be fixed for `CommonJs` in this version. Please, check the [version 3.5.4](https://www.npmjs.com/package/postcss-rtlcss/v/3.5.4) and let me know if your issue gets solved.
Regards.

**Comment by elchininet** [comment] 2022-04-04 17:14
Hi @catrope,
It seems that the issue is already resolved. Closing this issue.
Regards

**Closed** 2022-04-04 17:14 UTC

**Comment by catrope** [comment] 2022-04-04 17:19
Yes, this new version works great, thanks! Sorry for forgetting to leave a comment here on Friday

**Comment by elchininet** [comment] 2022-04-04 17:24
@catrope, no worries.
Glad to hear that the issue is solved.
Regards
